### ISSUE TITLE
Is this step still maintained?

### ISSUE THREAD

**Issue by BirmacherAkos** [vladimirpetrovski/bitrise-step-version-extractor-android#6]
Hey @vladimirpetrovski 
Akos here from Bitrise.
First of all, I'd like to thank you for all of your hard work with this step and for helping the Bitrise community. 🚀

I'm reaching out to you as we are working on keeping the Bitrise step library up to date by deprecating the [abandoned steps](https://devcenter.bitrise.io/en/steps-and-workflows/developing-your-own-bitrise-step/sharing-steps-with-all-bitrise-users.html#abandoned-steps) that are not maintained anymore.  🧹
We saw some older open issues for your step with no response. 

Could you please let me know your intentions with the step? 
If you don't have time to work on the step, then we may deprecate it from the step library.

**Comment by vladimirpetrovski** [comment]
Hi @BirmacherAkos, thank you for your message. I'm currently not maintaining this step. If you or anyone else wants to take over, I'm happy to transfer it. Thanks for understanding.

**Comment by BirmacherAkos** [comment]
Thanks @vladimirpetrovski .
Yes, it's understandable, I know how much plus effort requires maintaining a Step. 😄 
We don't plan to make it a Bitrise maintained Step yet, thus we'll tag it as a deprecated Step in the Step Library.
Users already using the Step can continue to use it, but the Step will be hidden in the workflow editor.

This deprecation is not final and can be re-done anytime if you or somebody else pick up the development of the Step later. 
Thanks again for your work with the Step. 🚀 

_I'm closing the issue, but let me know if you have any questions._
